version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ML_SERVICE_URL=http://ml-service:9000
    depends_on:
      - ml-service
    volumes:
      - ./backend/datasets:/app/datasets
      - ./backend/public:/app/public

  frontend:
    image: node:18
    working_dir: /app/frontend
    command: sh -c "npm install && npm run dev -- --host --port 5173"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
      - ./src:/app/frontend/src

  ml-service:
    build:
      context: .
      dockerfile: ml/prediction_service/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./ml:/app/ml
      - ./backend/datasets:/app/backend/datasets

